"""Request correlation and access logging.

The problem this solves: `logger.exception("retrieval failed")` in routes.py
produces a traceback, but with several users in flight there is nothing tying
that traceback to the request that caused it, or to the access-log line recording
its status and latency. You end up guessing.

So each request gets an id, stored in a ContextVar. A ContextVar - not a global,
and not a parameter threaded through every function - because it is scoped to the
current async task: two concurrent requests see two different values, and code
deep in the call stack can read it without the intervening functions knowing it
exists. A logging.Filter copies it onto every LogRecord, so the id appears on
application logs and the access log alike without any call site opting in.

Header echo is intentional: if a client sends X-Request-ID we keep it, so an id
generated by a load balancer or a frontend survives into these logs and traces
across the whole hop chain.
"""

import logging
import time
import uuid
from contextvars import ContextVar

from starlette.requests import Request

logger = logging.getLogger("app.access")

# Default "-" so logs emitted outside any request (startup, shutdown, scripts)
# still format cleanly instead of raising KeyError inside the logging module.
_request_id: ContextVar[str] = ContextVar("request_id", default="-")

REQUEST_ID_HEADER = "X-Request-ID"


def current_request_id() -> str:
    return _request_id.get()


class RequestIdFilter(logging.Filter):
    """Attach the current request id to every record.

    A Filter rather than a custom Formatter or a LoggerAdapter: filters run for
    records from *any* logger, including uvicorn's and httpx's, so third-party
    log lines get correlated too.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        record.request_id = _request_id.get()
        return True          # never actually filters anything out


async def log_requests(request: Request, call_next):
    """Assign a request id, then log one line per request with its outcome."""
    # uuid4().hex[:12] is short enough to scan in a terminal and still has
    # ~10^14 values, which is plenty for correlating within a log retention
    # window. It is not a security token and is never used as one.
    rid = request.headers.get(REQUEST_ID_HEADER) or uuid.uuid4().hex[:12]
    token = _request_id.set(rid)
    t0 = time.perf_counter()
    try:
        response = await call_next(request)
    except Exception:
        # Unhandled below us: log with the id, then re-raise so FastAPI's
        # handler still turns it into a 500. Swallowing it would hide bugs.
        logger.exception("%s %s -> unhandled exception",
                         request.method, request.url.path)
        raise
    finally:
        # reset() rather than leaving it set: the ContextVar outlives this
        # coroutine, so a stale id could leak into unrelated logging.
        _request_id.reset(token)

    logger.info("%s %s -> %d in %.1fms rid=%s", request.method, request.url.path,
                response.status_code, (time.perf_counter() - t0) * 1000, rid)
    # Echo the id back so a client can quote it in a bug report.
    response.headers[REQUEST_ID_HEADER] = rid
    return response
